# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 08:37
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(auto_now=True, help_text='The date this activity was recorded.', verbose_name='when')),
            ],
            options={
                'verbose_name': 'ActivityLog',
                'verbose_name_plural': 'ActivityLogs',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('name', models.CharField(help_text='Category name.', max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, verbose_name='slug')),
                ('name', models.CharField(help_text='User-supplied dataset name.', max_length=256, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='User-supplied dataset description.', verbose_name='description')),
                ('column_schema', jsonfield.fields.JSONField(default=None, help_text='Metadata about columns.', null=True, verbose_name='column_schema')),
                ('sample_data', jsonfield.fields.JSONField(default=None, help_text='Example data rows from the dataset.', null=True, verbose_name='sample_data')),
                ('row_count', models.IntegerField(blank=True, help_text='The number of rows in this dataset. Null if no data has been added/imported.', null=True, verbose_name='row_count')),
                ('creation_date', models.DateTimeField(help_text='The date this dataset was initially created.', null=True, verbose_name='creation_date')),
                ('last_modified', models.DateTimeField(blank=True, default=None, help_text='When, if ever, was this dataset last modified via the API?', null=True, verbose_name='last_modified')),
                ('last_modification', models.TextField(blank=True, default=None, help_text='Description of the last modification made to this Dataset.', null=True, verbose_name='last_modification')),
                ('locked', models.BooleanField(default=False, help_text='Is this table locked for writing?', verbose_name='locked')),
                ('locked_at', models.DateTimeField(default=None, help_text='Time this dataset was last locked.', null=True, verbose_name='locked_at')),
                ('related_links', jsonfield.fields.JSONField(default=[])),
                ('categories', models.ManyToManyField(blank=True, help_text='Categories containing this Dataset.', null=True, related_name='datasets', to='panda.Category', verbose_name='categories')),
            ],
            options={
                'ordering': ['-creation_date'],
                'verbose_name': 'Dataset',
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Filename as stored in PANDA.', max_length=256, verbose_name='filename')),
                ('original_filename', models.CharField(help_text='Filename as originally uploaded.', max_length=256, verbose_name='original_filename')),
                ('size', models.IntegerField(help_text='Size of the file in bytes.', verbose_name='size')),
                ('creation_date', models.DateTimeField(help_text='The date this file was uploaded.', verbose_name='creation_date')),
                ('title', models.TextField(help_text='A user-friendly name for this file.', max_length=256, verbose_name='title')),
                ('data_type', models.CharField(blank=True, help_text='The type of this file, if known.', max_length=4, null=True, verbose_name='data_type')),
                ('encoding', models.CharField(default=b'utf-8', help_text='The character encoding of this file. Defaults to utf-8', max_length=32, verbose_name='encoding')),
                ('dialect', jsonfield.fields.JSONField(help_text='Description of the formatting of this file.', null=True, verbose_name='dialect')),
                ('columns', jsonfield.fields.JSONField(help_text='A list of names for the columns in this upload.', null=True, verbose_name='columns')),
                ('sample_data', jsonfield.fields.JSONField(help_text='Example data from this file.', null=True, verbose_name='sample_data')),
                ('guessed_types', jsonfield.fields.JSONField(help_text='Column types guessed based on a sample of data.', null=True, verbose_name='guessed_types')),
                ('imported', models.BooleanField(default=False, help_text='Has this upload ever been imported into its parent dataset.', verbose_name='imported')),
                ('deletable', models.BooleanField(default=True, help_text='Can this data upload be deleted? False for uploads prior to 1.0.', verbose_name='deletable')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'DataUpload',
                'verbose_name_plural': 'DataUploads',
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Filename as stored in PANDA.', max_length=256, verbose_name='filename')),
                ('original_filename', models.CharField(help_text='Filename as originally uploaded.', max_length=256, verbose_name='original_filename')),
                ('size', models.IntegerField(help_text='Size of the file in bytes.', verbose_name='size')),
                ('creation_date', models.DateTimeField(help_text='The date this file was uploaded.', verbose_name='creation_date')),
                ('title', models.TextField(help_text='A user-friendly name for this file.', max_length=256, verbose_name='title')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'Export',
                'verbose_name_plural': 'Exports',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The message to deliver.', verbose_name='message')),
                ('type', models.CharField(choices=[(b'Info', 'Info'), (b'Warning', 'Warning'), (b'Error', 'Error')], default=b'Info', help_text='The type of message: info, warning or error', max_length=16, verbose_name='type')),
                ('sent_at', models.DateTimeField(auto_now=True, help_text='When this notification was created', verbose_name='sent_at')),
                ('read_at', models.DateTimeField(blank=True, default=None, help_text='When this notification was read by the user.', null=True, verbose_name='read_at')),
                ('url', models.URLField(default=None, help_text='A url to link to when displaying this notification.', null=True, verbose_name='url')),
            ],
            options={
                'ordering': ['-sent_at'],
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='RelatedUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='Filename as stored in PANDA.', max_length=256, verbose_name='filename')),
                ('original_filename', models.CharField(help_text='Filename as originally uploaded.', max_length=256, verbose_name='original_filename')),
                ('size', models.IntegerField(help_text='Size of the file in bytes.', verbose_name='size')),
                ('creation_date', models.DateTimeField(help_text='The date this file was uploaded.', verbose_name='creation_date')),
                ('title', models.TextField(help_text='A user-friendly name for this file.', max_length=256, verbose_name='title')),
            ],
            options={
                'ordering': ['creation_date'],
                'verbose_name': 'RelatedUpload',
                'verbose_name_plural': 'RelatedUploads',
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The search query that was executed', max_length=4096, verbose_name='query')),
                ('when', models.DateTimeField(auto_now=True, help_text='The date and time this search was logged.', verbose_name='when')),
                ('dataset', models.ForeignKey(default=None, help_text='The data set searched, or null if all were searched.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='panda.Dataset', verbose_name='dataset')),
            ],
            options={
                'verbose_name': 'SearchLog',
                'verbose_name_plural': 'SearchLogs',
            },
        ),
        migrations.CreateModel(
            name='SearchSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(help_text='The search query to executed.', max_length=256, verbose_name='query')),
                ('query_url', models.CharField(help_text='Query encoded for URL.', max_length=256, verbose_name='query_url')),
                ('query_human', models.TextField(help_text='Human-readable description of the query being run.', verbose_name='query_human')),
                ('last_run', models.DateTimeField(auto_now=True, help_text='The last time this search this was run.', verbose_name='last_run')),
                ('category', models.ForeignKey(default=None, help_text='A category to be searched or null if all are to be searched.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_subscriptions', to='panda.Category', verbose_name='category')),
                ('dataset', models.ForeignKey(default=None, help_text='The dataset to be searched or null if all are to be searched.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_subscriptions', to='panda.Dataset', verbose_name='dataset')),
            ],
            options={
                'verbose_name': 'SearchSubscription',
                'verbose_name_plural': 'SearchSubscriptions',
            },
        ),
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(help_text='Identifying name for this task.', max_length=255, verbose_name='task_name')),
                ('task_description', models.TextField(help_text='Description of the task.', verbose_name='task_description')),
                ('status', models.CharField(choices=[(b'FAILURE', b'FAILURE'), (b'PENDING', b'PENDING'), (b'RECEIVED', b'RECEIVED'), (b'RETRY', b'RETRY'), (b'REVOKED', b'REVOKED'), (b'STARTED', b'STARTED'), (b'SUCCESS', b'SUCCESS'), (b'ABORTED', b'ABORTED'), (b'ABORT REQUESTED', b'ABORT REQUESTED')], default=b'PENDING', help_text='Current state of this task.', max_length=50, verbose_name='status')),
                ('message', models.CharField(blank=True, help_text='A human-readable message indicating the progress of this task.', max_length=255, verbose_name='message')),
                ('start', models.DateTimeField(help_text='Date and time that this task began processing.', null=True, verbose_name='start')),
                ('end', models.DateTimeField(help_text='Date and time that this task ceased processing (either complete or failed).', null=True, verbose_name='end')),
                ('traceback', models.TextField(blank=True, default=None, help_text='Traceback that exited this task, if it failed.', null=True, verbose_name='traceback')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='activation_key')),
                ('activation_key_expiration', models.DateTimeField(verbose_name='activation_key_expiration')),
                ('show_login_help', models.BooleanField(default=True, help_text=b'This field is no longer used.', verbose_name='show_login_help')),
            ],
            options={
                'verbose_name': 'UserProfile',
                'verbose_name_plural': 'UserProfiles',
            },
        ),
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'User',
                'proxy': True,
                'verbose_name_plural': 'Users',
                'indexes': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panda.UserProxy', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='creator',
            field=models.ForeignKey(help_text='The user who initiated this task.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='panda.UserProxy', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='searchsubscription',
            name='user',
            field=models.ForeignKey(help_text='The user who subscribed to the search.', on_delete=django.db.models.deletion.CASCADE, related_name='search_subscriptions', to='panda.UserProxy', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='searchlog',
            name='user',
            field=models.ForeignKey(help_text='The user who executed the search.', on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to='panda.UserProxy', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='relatedupload',
            name='creator',
            field=models.ForeignKey(help_text='The user who uploaded this file.', on_delete=django.db.models.deletion.CASCADE, to='panda.UserProxy', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='relatedupload',
            name='dataset',
            field=models.ForeignKey(help_text='The dataset this upload is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='related_uploads', to='panda.Dataset', verbose_name='dataset'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='The user who should receive this notification.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='panda.UserProxy', verbose_name='recipient'),
        ),
        migrations.AddField(
            model_name='export',
            name='creator',
            field=models.ForeignKey(help_text='The user who uploaded this file.', on_delete=django.db.models.deletion.CASCADE, to='panda.UserProxy', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='export',
            name='dataset',
            field=models.ForeignKey(help_text='The dataset this export is from.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='panda.Dataset', verbose_name='dataset'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='creator',
            field=models.ForeignKey(help_text='The user who uploaded this file.', on_delete=django.db.models.deletion.CASCADE, to='panda.UserProxy', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='dataupload',
            name='dataset',
            field=models.ForeignKey(help_text='The dataset this upload is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_uploads', to='panda.Dataset', verbose_name='dataset'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='creator',
            field=models.ForeignKey(help_text='The user who created this dataset.', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='panda.UserProxy', verbose_name='creator'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='current_task',
            field=models.ForeignKey(blank=True, help_text='The currently executed or last finished task related to this dataset.', null=True, on_delete=django.db.models.deletion.CASCADE, to='panda.TaskStatus', verbose_name='current_task'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='initial_upload',
            field=models.ForeignKey(blank=True, help_text='The data upload used to create this dataset, if any was used.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initial_upload_for', to='panda.DataUpload', verbose_name='initial_upload'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user, if any, who last modified this dataset.', null=True, on_delete=django.db.models.deletion.CASCADE, to='panda.UserProxy', verbose_name='last_modified_by'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(help_text='The user who was active.', on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='panda.UserProxy', verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='activitylog',
            unique_together=set([('user', 'when')]),
        ),
    ]
